name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache test
      id: cache-test
      uses: actions/cache@v3
      with:
        path: test.txt
        key: ${{ runner.os }}-test-${{ github.run_id }}
        restore-keys: |
          ${{ runner.os }}-test

    - name: Make test file
      run: |
        echo "${{ github.run_id }}" >> test.txt

    - name: Print test file
      run: |
        cat test.txt

