name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache test
      id: cache-test
      uses: actions/cache@v3
      with:
        path: test.txt
        key: ${{ runner.os }}-test

    - name: Make test file
      run: |
        echo "${{ github.run_id }}" >> test.txt

    - name: Print test file
      run: |
        cat test.txt

    - name: List cache
      run: |
        gh api -H "Accept: application/vnd.github+json" /repos/hinerm/cache-tests/actions/caches?key=${{ runner.os }}-test
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

    - name: Delete cache
      if: steps.cache-test.outputs.cache-hit == 'true'
      run: |
        gh api --method DELETE -H "Accept: application/vnd.github+json" /repos/hinerm/cache-tests/actions/caches?key=${{ runner.os }}-test
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

    - name: Update cache post-delete
      if: steps.cache-test.outputs.cache-hit == 'true'
      id: update-cache
      uses: actions/cache@v3
      with:
        path: test.txt
        key: ${{ runner.os }}-test
